name: Build and Release Queemo

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Git and push tag
        run: |
          git config user.name "alfred-jerobas"
          git config user.email "jerobas.alfred@gmail.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/jerobas/queemo.git
      
          echo "🔍 Git remote after setting:"
          git remote -v
      
          npx standard-version --no-verify
          git push --follow-tags origin master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Build app
        run: npm run build-publish
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}